# Generated by Django 2.1.7 on 2020-01-13 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='people',
        ),
        migrations.RenameField(
            model_name='commenttask',
            old_name='Users',
            new_name='people',
        ),
        migrations.RenameField(
            model_name='taskdetails',
            old_name='Users',
            new_name='people',
        ),
    ]
