# Generated by Django 2.1.7 on 2020-01-13 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200113_1654'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='people',
            new_name='Users',
        ),
        migrations.RenameField(
            model_name='commenttask',
            old_name='people',
            new_name='Users',
        ),
        migrations.RenameField(
            model_name='taskdetails',
            old_name='people',
            new_name='Users',
        ),
    ]
