# Generated by Django 2.1.7 on 2020-01-27 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200113_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskdetails',
            old_name='type',
            new_name='typ',
        ),
    ]
